### ISSUE TITLE
prefect.server.services.flowrunnotifications - Unexpected error in: OperationalError('(sqlite3.OperationalError) database is locked')

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#10188]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect server deployed with sqlite has log errors:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM flow_run_notification_queue WHERE flow_run_notification_queue.id IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1) RETURNING id]
```

### Reproduction

```python3
git clone git@github.com:tekumara/prefect-demo.git
cd prefect-demo

# create kubes cluster + deploy prefect
make kubes

# deploy and run some flows
make deploy

# check logs
make kubes-logs
```

### Error

```python3
08:08:08.962 | ERROR   | prefect.server.services.flowrunnotifications - Unexpected error in: OperationalError('(sqlite3.OperationalError) database is locked')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 263, in _handle_exception
    raise error
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/server/services/loop_service.py", line 78, in start
    await self.run_once()
  File "/usr/local/lib/python3.9/site-packages/prefect/server/database/dependencies.py", line 119, in async_wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/server/services/flow_run_notifications.py", line 38, in run_once
    notifications = await db.get_flow_run_notifications_from_queue(
  File "/usr/local/lib/python3.9/site-packages/prefect/server/database/interface.py", line 350, in get_flow_run_notifications_from_queue
    return await self.queries.get_flow_run_notifications_from_queue(
  File "/usr/local/lib/python3.9/site-packages/prefect/server/database/query_components.py", line 842, in get_flow_run_notifications_from_queue
    await session.execute(delete_stmt)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 439, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1936, in orm_execute_statement
    return super().orm_execute_statement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 263, in _handle_exception
    raise error
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM flow_run_notification_queue WHERE flow_run_notification_queue.id IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1) RETURNING id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Versions

```Text
Version:             2.10.20
API version:         0.8.4
Python version:      3.9.13
Git commit:          08326f42
Built:               Fri, Jul 7, 2023 3:22 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
```

### Additional context

Deployed using helm chart 2023.07.07 with _values.yaml_:
```yaml
server:
  image:
    prefectTag: 2.10.20-python3.9

postgresql:
  # use sqlite instead
  enabled: false
  useSubChart: false
```

**Comment by VisalDataU** [comment]
I remember one time this error caused one of my flows to fail to run, so I have to set PREFECT_API_SERVICES_FLOW_RUN_NOTIFICATIONS_ENABLED=false to suppress it.

**Comment by bradh11** [comment]
Is there anything to be concerned with this error?  Suppressing the error seems like it is masking an issue to me rather than uncovering the root of why it is happening.

**Comment by jmrichardson** [comment]
Hi, how do I suppress this error message?  It is overwhelming the console.  I have tried this but no luck:  

import os
os.environ["PREFECT_API_SERVICES_FLOW_RUN_NOTIFICATIONS_ENABLED"] = "false"

Thanks in advance

**Comment by goFrendiAsgard** [comment]
@jmrichardson you can't do that from your Python script.
You need to modify the shell environment itself.

If you are using bash, you should run
```
export PREFECT_API_SERVICES_FLOW_RUN_NOTIFICATIONS_ENABLED=false
prefect start
```

**Comment by ddeepwell** [comment]
I am getting the same `sqlite3.OperationalError: database is locked` error under the following (and similar) scenario(s). 

1. Start with an empty ~/.prefect directory.
1. ```bash
   prefect server start
   ```
1. ```bash
   prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
   ```
1. Execute the following commands in separate terminals:
   ```bash
   prefect worker start --pool "poll-transfers"
   ```
   ```bash
   prefect worker start --pool "process"
   ```

I am using Prefect 3.3.3 on macOS 15.4 with Python 3.13.2.

**Comment by cicdw** [comment]
The Flow Run Notification service was removed in https://github.com/PrefectHQ/prefect/pull/17939 which was released with 3.4.0, so this particular version of DB instability should now be resolved.

**Comment by mirageAlchemy** [comment]
I am still getting `database is locked` errors despite already updated to 3.4.11. The sql query I have is slightly different though, I am getting:

```
ug 01 16:41:34 user uv[916528]: sqlite3.OperationalError: database is locked
Aug 01 16:41:34 user uv[916528]: The above exception was the direct cause of the following exception:
Aug 01 16:41:34 user uv[916528]: Traceback (most recent call last):
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/prefect/server/models/deployments.py", line 1118, in mark_deployments_ready
Aug 01 16:41:34 user uv[916528]:     await session.execute(
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 463, in execute
Aug 01 16:41:34 user uv[916528]:     result = await greenlet_spawn(
Aug 01 16:41:34 user uv[916528]:              ^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
Aug 01 16:41:34 user uv[916528]:     result = context.throw(*sys.exc_info())
Aug 01 16:41:34 user uv[916528]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
Aug 01 16:41:34 user uv[916528]:     return self._execute_internal(
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
Aug 01 16:41:34 user uv[916528]:     result: Result[Any] = compile_state_cls.orm_execute_statement(
Aug 01 16:41:34 user uv[916528]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1648, in orm_execute_statement
Aug 01 16:41:34 user uv[916528]:     return super().orm_execute_statement(
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
Aug 01 16:41:34 user uv[916528]:     result = conn.execute(
Aug 01 16:41:34 user uv[916528]:              ^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
Aug 01 16:41:34 user uv[916528]:     return meth(
Aug 01 16:41:34 user uv[916528]:            ^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
Aug 01 16:41:34 user uv[916528]:     return connection._execute_clauseelement(
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
Aug 01 16:41:34 user uv[916528]:     ret = self._execute_context(
Aug 01 16:41:34 user uv[916528]:           ^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
Aug 01 16:41:34 user uv[916528]:     return self._exec_single_context(
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
Aug 01 16:41:34 user uv[916528]:     self._handle_dbapi_exception(
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
Aug 01 16:41:34 user uv[916528]:     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
Aug 01 16:41:34 user uv[916528]:     self.dialect.do_execute(
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
Aug 01 16:41:34 user uv[916528]:     cursor.execute(statement, parameters)
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 149, in execute
Aug 01 16:41:34 user uv[916528]:     self._adapt_connection._handle_exception(error)
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 149, in execute
Aug 01 16:41:34 user uv[916528]:     self._adapt_connection._handle_exception(error)
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 300, in _handle_exception
Aug 01 16:41:34 user uv[916528]:     raise error
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 131, in execute
Aug 01 16:41:34 user uv[916528]:     self.await_(_cursor.execute(operation, parameters))
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
Aug 01 16:41:34 user uv[916528]:     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
Aug 01 16:41:34 user uv[916528]:     value = await result
Aug 01 16:41:34 user uv[916528]:             ^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/aiosqlite/cursor.py", line 40, in execute
Aug 01 16:41:34 user uv[916528]:     await self._execute(self._cursor.execute, sql, parameters)
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/aiosqlite/cursor.py", line 32, in _execute
Aug 01 16:41:34 user uv[916528]:     return await self._conn._execute(fn, *args, **kwargs)
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 122, in _execute
Aug 01 16:41:34 user uv[916528]:     return await future
Aug 01 16:41:34 user uv[916528]:            ^^^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]:   File "/home/deploy/code/cs/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 105, in run
Aug 01 16:41:34 user uv[916528]:     result = function()
Aug 01 16:41:34 user uv[916528]:              ^^^^^^^^^^
Aug 01 16:41:34 user uv[916528]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
Aug 01 16:41:34 user uv[916528]: [SQL: UPDATE deployment SET last_polled=:last_polled, status=:status, updated=strftime('%Y-%m-%d %H:%M:%f000', 'now') WHERE deployment.id IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1) OR deployment.work_queue_id IN (:work_queue_id_1_1)]
Aug 01 16:41:34 user uv[916528]: [parameters: {'last_polled': '2025-08-01 08:41:34.287229', 'status': 'READY', 'work_queue_id_1_1': '131f4b4f-1e26-4249-9782-75b9c13ffce5'}]
```

I deployed a local workpool along with the server at the same machine, dont know if it is related.

**Comment by petrdvor** [comment]
Database is locked:

```
flows-prefect-server-1  | 09:45:33.897 | ERROR   | prefect.server.models.deployments - Error marking deployments as ready: (sqlite3.OperationalError) database is locked
flows-prefect-server-1  | [SQL: UPDATE deployment SET last_polled=:last_polled, status=:status, updated=strftime('%Y-%m-%d %H:%M:%f000', 'now') WHERE deployment.id IN (:id_1_1) OR deployment.work_queue_id IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1)]
flows-prefect-server-1  | [parameters: {'last_polled': '2025-08-13 09:45:33.895108', 'status': 'READY', 'id_1_1': '80b5254e-4b2f-4de3-8c6b-6d4317ced151'}]
flows-prefect-server-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
flows-prefect-server-1  | Traceback (most recent call last):
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
flows-prefect-server-1  |     self.dialect.do_execute(
flows-prefect-server-1  |     ~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         cursor, str_statement, effective_parameters, context
flows-prefect-server-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
flows-prefect-server-1  |     cursor.execute(statement, parameters)
flows-prefect-server-1  |     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 177, in execute
flows-prefect-server-1  |     self._adapt_connection._handle_exception(error)
flows-prefect-server-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 337, in _handle_exception
flows-prefect-server-1  |     raise error
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 159, in execute
flows-prefect-server-1  |     self.await_(_cursor.execute(operation, parameters))
flows-prefect-server-1  |     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
flows-prefect-server-1  |     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
flows-prefect-server-1  |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
flows-prefect-server-1  |     value = await result
flows-prefect-server-1  |             ^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/cursor.py", line 40, in execute
flows-prefect-server-1  |     await self._execute(self._cursor.execute, sql, parameters)
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/cursor.py", line 32, in _execute
flows-prefect-server-1  |     return await self._conn._execute(fn, *args, **kwargs)
flows-prefect-server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/core.py", line 122, in _execute
flows-prefect-server-1  |     return await future
flows-prefect-server-1  |            ^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/core.py", line 105, in run
flows-prefect-server-1  |     result = function()
flows-prefect-server-1  | sqlite3.OperationalError: database is locked
flows-prefect-server-1  | 
flows-prefect-server-1  | The above exception was the direct cause of the following exception:
flows-prefect-server-1  | 
flows-prefect-server-1  | Traceback (most recent call last):
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/prefect/server/models/deployments.py", line 1118, in mark_deployments_ready
flows-prefect-server-1  |     await session.execute(
flows-prefect-server-1  |     ...<8 lines>...
flows-prefect-server-1  |     )
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 463, in execute
flows-prefect-server-1  |     result = await greenlet_spawn(
flows-prefect-server-1  |              ^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     ...<6 lines>...
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
flows-prefect-server-1  |     result = context.throw(*sys.exc_info())
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
flows-prefect-server-1  |     return self._execute_internal(
flows-prefect-server-1  |            ~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         statement,
flows-prefect-server-1  |         ^^^^^^^^^^
flows-prefect-server-1  |     ...<4 lines>...
flows-prefect-server-1  |         _add_event=_add_event,
flows-prefect-server-1  |         ^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
flows-prefect-server-1  |     result: Result[Any] = compile_state_cls.orm_execute_statement(
flows-prefect-server-1  |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         self,
flows-prefect-server-1  |         ^^^^^
flows-prefect-server-1  |     ...<4 lines>...
flows-prefect-server-1  |         conn,
flows-prefect-server-1  |         ^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1660, in orm_execute_statement
flows-prefect-server-1  |     return super().orm_execute_statement(
flows-prefect-server-1  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         session,
flows-prefect-server-1  |         ^^^^^^^^
flows-prefect-server-1  |     ...<4 lines>...
flows-prefect-server-1  |         conn,
flows-prefect-server-1  |         ^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
flows-prefect-server-1  |     result = conn.execute(
flows-prefect-server-1  |         statement, params or {}, execution_options=execution_options
flows-prefect-server-1  |     )
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1419, in execute
flows-prefect-server-1  |     return meth(
flows-prefect-server-1  |         self,
flows-prefect-server-1  |         distilled_parameters,
flows-prefect-server-1  |         execution_options or NO_OPTIONS,
flows-prefect-server-1  |     )
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/sql/elements.py", line 526, in _execute_on_connection
flows-prefect-server-1  |     return connection._execute_clauseelement(
flows-prefect-server-1  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         self, distilled_params, execution_options
flows-prefect-server-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1641, in _execute_clauseelement
flows-prefect-server-1  |     ret = self._execute_context(
flows-prefect-server-1  |         dialect,
flows-prefect-server-1  |     ...<8 lines>...
flows-prefect-server-1  |         cache_hit=cache_hit,
flows-prefect-server-1  |     )
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
flows-prefect-server-1  |     return self._exec_single_context(
flows-prefect-server-1  |            ~~~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         dialect, context, statement, parameters
flows-prefect-server-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
flows-prefect-server-1  |     self._handle_dbapi_exception(
flows-prefect-server-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         e, str_statement, effective_parameters, cursor, context
flows-prefect-server-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
flows-prefect-server-1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
flows-prefect-server-1  |     self.dialect.do_execute(
flows-prefect-server-1  |     ~~~~~~~~~~~~~~~~~~~~~~~^
flows-prefect-server-1  |         cursor, str_statement, effective_parameters, context
flows-prefect-server-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |     )
flows-prefect-server-1  |     ^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
flows-prefect-server-1  |     cursor.execute(statement, parameters)
flows-prefect-server-1  |     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 177, in execute
flows-prefect-server-1  |     self._adapt_connection._handle_exception(error)
flows-prefect-server-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 337, in _handle_exception
flows-prefect-server-1  |     raise error
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 159, in execute
flows-prefect-server-1  |     self.await_(_cursor.execute(operation, parameters))
flows-prefect-server-1  |     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
flows-prefect-server-1  |     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
flows-prefect-server-1  |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
flows-prefect-server-1  |     value = await result
flows-prefect-server-1  |             ^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/cursor.py", line 40, in execute
flows-prefect-server-1  |     await self._execute(self._cursor.execute, sql, parameters)
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/cursor.py", line 32, in _execute
flows-prefect-server-1  |     return await self._conn._execute(fn, *args, **kwargs)
flows-prefect-server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/core.py", line 122, in _execute
flows-prefect-server-1  |     return await future
flows-prefect-server-1  |            ^^^^^^^^^^^^
flows-prefect-server-1  |   File "/usr/local/lib/python3.13/site-packages/aiosqlite/core.py", line 105, in run
flows-prefect-server-1  |     result = function()
flows-prefect-server-1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
flows-prefect-server-1  | [SQL: UPDATE deployment SET last_polled=:last_polled, status=:status, updated=strftime('%Y-%m-%d %H:%M:%f000', 'now') WHERE deployment.id IN (:id_1_1) OR deployment.work_queue_id IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1)]
flows-prefect-server-1  | [parameters: {'last_polled': '2025-08-13 09:45:33.895108', 'status': 'READY', 'id_1_1': '80b5254e-4b2f-4de3-8c6b-6d4317ced151'}]
flows-prefect-server-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
```


Server is local, in docker.

```Version:             3.4.12
API version:         0.8.4
Python version:      3.13.5
Git commit:          35e04f52
Built:               Fri, Aug 08, 2025 10:41 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         ephemeral
Pydantic version:    2.11.7
Server:
  Database:          sqlite
  SQLite version:    3.34.1```

Flows run, this error floods the terminal.

**Comment by torext** [comment]
> The Flow Run Notification service was removed in [#17939](https://github.com/PrefectHQ/prefect/pull/17939) which was released with 3.4.0, so this particular version of DB instability should now be resolved.

It's not however, same as @mirageAlchemy above I still keep getting these errors when checking `journalctl`.
