### ISSUE TITLE
`result_async()` always timeout when accessing results from background task created using `delay()`

### ISSUE THREAD

**Issue by pratheekrebala** [PrefectHQ/prefect#18278]
### Bug summary

I am triggering a background task using the `delay()` method and trying to access the result by awaiting the `result_async()` method. If the task isn't completed by the time a call to `result_async()` is made, it always raises an incorrect `TimeoutError`. I believe this is a bug in how the `_final_state` value is checked here:

https://github.com/PrefectHQ/prefect/blob/90f261bc0c06e5fc6cda92e83c39ff5131f6d52a/src/prefect/futures.py#L289-L301

The promise correctly waits until the task is completed but the `TimeoutError` is consistently triggered because `_final_state` is never set. Unless of course, the task is already completed by the time the call to `result_async()` is made. 

To reproduce this:

1. Create a `background_worker.py` file:

```python
from prefect import flow, task
from prefect.task_worker import serve
import time

@task
async def background_task():
    time.sleep(10)

if __name__ == '__main__':
    serve(background_task)
```

2. Run the worker: `python background_worker.py`

3. While that is running, call the background task from another script:

```python
from background_worker import background_task

task = background_task.delay()
result = await task.result_async(timeout = 100) # this will always trigger a timeout unless task is already completed when this method is called. It will however, block until the result is completed.
```

It seems like the only way to make this work is to separately wait for the task by doing:

```
task = background_task.delay()
await task.wait_async()
result = await task.result_async()
```

Is there a way to make this workflow work? Or am I doing something incorrectly here? I'm hoping to effectively launch a background task and wait for it's results asynchronously.

### Version info

```Text
Version:             3.4.5
API version:         0.8.4
Python version:      3.11.2
Git commit:          df37c8cf
Built:               Sat, Jun 07, 2025 02:24 AM
OS/Arch:             linux/aarch64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.11.5
Integrations:
  prefect-dask:      0.3.5
```

**Comment by zzstoatzz** [comment]
thanks for the issue @pratheekrebala - this should now be fixed on `main` - let me know if you have a chance to test it before we release 3.4.7!

**Comment by Symsystem** [comment]
Hello @zzstoatzz , 

I use Prefect 3.4.15 and I still encounter this issue very often, randomly:
The fix that has been made reduces the risk of the error a little bit because it calls the API [a second time](https://github.com/PrefectHQ/prefect/pull/18280/files#diff-0fd5aa2741e7e57b455920e807c2939c5741ca22be14a16172000c48754aa5ccR313-R320), but the code is still subject to race conditions: when it calls `client.read_task_run(task_run_id=self._task_run_id)` a second time right after the first one, nothing ensures the task run state has been updated in the API.

I'm doing exactly as @pratheekrebala does in his code:

```python
task = background_task.with_options(name="custom_name").delay()
result = await task.async_result()
```

This raises a TimeoutError (of course no timeout has been set). 
I printed the state retrieved from the client, the second time, just before the error is raised; it shows me "RUNNING" (while in the server it is properly "COMPLETED").

=> I use a self-hosted prefect server, in a docker-compose for dev and in Kubernetes for staging / prod.

Should we reopen that issue ?

**Comment by PierreColombo** [comment]
I'm encountering the same problem 💯
