### ISSUE TITLE
Block's type dispatch breaks Pydantic validation of multiple Blocks in Union

### ISSUE THREAD

**Issue by GalLadislav** [PrefectHQ/prefect#18919]
### Bug summary

Hello Prefect Team!

We have into an issue when using Union of multiple Blocks as attribute of other Blocks/BaseModels. The inner Blocks comes out not properly initialized (not having their attributes) or the parent validation fails right away if any of those Blocks have validators accessing their own attributes in "after" validation. 

Here are two minimal examples:
```python
# Attribute error after validation
import pydantic
from prefect.blocks.core import Block
from typing import Union


class MyInnerBlock1(Block):
    name1: str = pydantic.Field(default="inner-block1")


class MyInnerBlock2(Block):
    name2: str = pydantic.Field(default="inner-block2")


class MyOuterBlock(Block):
    inner: Union[MyInnerBlock1, MyInnerBlock2]
    name: str = pydantic.Field(default="outer-block")


my_block = MyOuterBlock(inner=MyInnerBlock2())
my_block_ser = my_block.model_dump()
my_block_deser = MyOuterBlock.model_validate(my_block_ser)
print(my_block_deser.inner.name2)  # NOK = AttributeError

"""
Traceback (most recent call last):
  File ".../.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3672, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-2-e78b5607e3e8>", line 23, in <module>
    print(my_block_deser.inner.name2)  # NOK = AttributeError
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/pydantic/main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'MyInnerBlock2' object has no attribute 'name2'
"""
```

```python
# Attribute error during validation
import pydantic
from prefect.blocks.core import Block
from typing import Union


class MyInnerBlock1(Block):
    name1: str = pydantic.Field(default="inner-block1")

    @pydantic.model_validator(mode="after")
    def validate_model(self) -> "MyInnerBlock1":
        if self.name1 is None:
            self.name1 = "Hello from inner block!"
        return self


class MyInnerBlock2(Block):
    name2: str = pydantic.Field(default="inner-block2")

    @pydantic.model_validator(mode="after")
    def validate_model(self) -> "MyInnerBlock2":
        if self.name2 is None:
            self.name2 = "Hello from inner block!"
        return self


class MyOuterBlock(Block):
    inner: Union[MyInnerBlock1, MyInnerBlock2]
    name: str = pydantic.Field(default="outer-block")


my_block = MyOuterBlock(inner=MyInnerBlock2())
my_block_ser = my_block.model_dump()
my_block_deser = MyOuterBlock.model_validate(my_block_ser)  # NOK = AttributeError

"""
Traceback (most recent call last):
  File ".../.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3672, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-2-c6870d251d7a>", line 34, in <module>
    my_block_deser = MyOuterBlock.model_validate(my_block_ser)  # NOK = AttributeError
  File ".../src/prefect/blocks/core.py", line 1622, in model_validate
    return super().model_validate(
           ~~~~~~~~~~~~~~~~~~~~~~^
        obj,
        ^^^^
    ...<2 lines>...
        context=context,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File ".../.venv/lib/python3.13/site-packages/pydantic/main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File ".../src/prefect/blocks/core.py", line 335, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "<ipython-input-2-c6870d251d7a>", line 12, in validate_model
    if self.name1 is None:
       ^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/pydantic/main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'MyInnerBlock2' object has no attribute 'name1'
"""
```

Investigation notes:
- these issues happen only for multiple Blocks in union (can be combined with other types, e.g. pydantic BaseModel)
- does not matter if the parent model is a Block or Pydantic BaseModel
- if first block in union is the right type, everything works fine
- if first block in union is the wrong type, validation breaks, resulting in not initialized correct Block in union
- validation of parent model raises AttributeError if inner Block has validators accessing its own fields (mode="after")
- union_mode does not affect the issue

### Possible cause / fix:

It looks like the issue stems from the `__new__` method of Block. Pydantic does not like class changes by the type dispatch when validating union types. Modifying it so that it only looks for the correct Block type when block_type_slug is set and `cls is Block` resolves the issue. After that change, `Block.model_validate()` still picks the correct class based on block_type_slug. Sadly it breaks the type dispatch for Block subclasses.

Would this be the right approach? If so, I’m happy to open a PR with the fix.

### Version info

```Text
Version:              3.4.17
API version:          0.8.4
Python version:       3.12.11
Git commit:           7804f5f7
Built:                Fri, Sep 05, 2025 07:11 PM
OS/Arch:              darwin/arm64
Profile:              ephemeral
Server type:          ephemeral
Pydantic version:     2.11.7
Server:
  Database:           sqlite
  SQLite version:     3.49.1
Integrations:
  prefect-email:      0.4.2
```

### Additional context

I have noticed that similar issue with Pydantic models not being properly initialized happened in #18151. There might be some correlation?

**Comment by zzstoatzz** [comment]
hi @GalLadislav - thanks for the thorough report! we'll take a look at this

**Comment by zzstoatzz** [comment]
this should be addressed by https://github.com/PrefectHQ/prefect/pull/18920

**Comment by GalLadislav** [comment]
Hi @zzstoatzz , my PR you mentioned did not purposefully addressed this particular issue. After quick check, the issue still occurs on current main branch.

**Comment by zzstoatzz** [comment]
my mistake @GalLadislav - I've re-opened this
