### ISSUE TITLE
prefect.yaml jinja template trigger deployment broken in 3.6.3

### ISSUE THREAD

**Issue by rjgildea** [PrefectHQ/prefect#19501]
### Bug summary

Using prefect 3.6.3 to deploy a flow from prefect.yaml with jinja template trigger definitions prefect 3.6.3 the parameters are empty in the resulting automation action. With prefect 3.6.2 the automation action contains the parameters as expected.

flow.py:
```python
from prefect import flow


@flow
def say_hello(name: str) -> str:
    return f"Hello, {name}!"
```

prefect.yaml:
```yaml
deployments:
  - name: say-hello
    entrypoint: flow.py:say_hello
    work_pool:
      name: my-work-pool
    triggers:
      - type: event
        enabled: true
        match:
          prefect.resource.id: hello.world
        expect:
          - external.resource.pinged
        parameters:
          name: "{{ event.name }}"
```

Prefect 3.6.2 works as expected - i.e. `parameters={'name': '{{ event.name }}'}`:
```bash
$ uvx prefect@3.6.2 --no-prompt deploy --prefect-file prefect.yaml --all
$ uvx prefect@3.6.2 automation inspect say-hello__automation_1
[
    Automation(
        name='say-hello__automation_1',
        tags=[],
        trigger=EventTrigger(
            match=ResourceSpecification(root={'prefect.resource.id': 'hello.world'}),
            match_related=ResourceSpecification(root={}),
            after=set(),
            expect={'external.resource.pinged'},
            for_each=set()
        ),
        actions=[
            RunDeployment(
                deployment_id=UUID('fc5ab915-d4ca-4c07-bbea-31859d2fa082'),
                parameters={'name': '{{ event.name }}'},
                schedule_after=datetime.timedelta(0)
            )
        ],
        actions_on_trigger=[],
        actions_on_resolve=[],
        id='f0c33e73-5bc7-4123-a9f8-bf156e5c964e'
    )
]
```

With prefect 3.6.3 the parameters are empty - i.e. `parameters={}`:
```bash
$ uvx prefect@3.6.3 --no-prompt deploy --prefect-file prefect.yaml --all
$ uvx prefect@3.6.3 automation inspect say-hello__automation_1
[
    Automation(
        name='say-hello__automation_1',
        tags=[],
        trigger=EventTrigger(
            match=ResourceSpecification(root={'prefect.resource.id': 'hello.world'}),
            match_related=ResourceSpecification(root={}),
            after=set(),
            expect={'external.resource.pinged'},
            for_each=set()
        ),
        actions=[RunDeployment(deployment_id=UUID('fc5ab915-d4ca-4c07-bbea-31859d2fa082'), parameters={}, schedule_after=datetime.timedelta(0))],
        actions_on_trigger=[],
        actions_on_resolve=[],
        id='b57cb8d3-dd49-4897-ab68-b8e50e1c05bb'
    )
]
```

### Version info

```Text
$ uvx prefect@3.6.3 version
Version:              3.6.3
API version:          0.8.4
Python version:       3.13.1
Git commit:           dbc96d7c
Built:                Wed, Nov 19, 2025 10:19 PM
OS/Arch:              darwin/arm64
Profile:              prefect-cloud
Server type:          cloud
Pydantic version:     2.12.4
Server:
  Database:           sqlite
  SQLite version:     3.47.1
```

### Additional context

The [release notes for Prefect 3.6.3](https://github.com/PrefectHQ/prefect/releases/tag/3.6.3) include:
> fix: validate deployment triggers after templating so jinja-based booleans work, should close https://github.com/PrefectHQ/prefect/issues/19348 by [@iclectic](https://github.com/iclectic) in https://github.com/PrefectHQ/prefect/pull/19414
which seems a likely culprit for this regression.

**Comment by fredrikhgrelland** [comment]
I see have the same problem.
Adding my case to this issue in case it helps narrow down:

**deployment not working any more**
```yaml
deployments:
  - name: load_tables_on_event
    version: *version
    entrypoint: src/sync/lib/prefect/flows.py:load_tables_on_event
    work_pool: *work_pool_2xlarge
    triggers:
      - name: run dlt load when dhub updated
        type: event
        enabled: true
        match:
          prefect.resource.name: ev_job_list_exp_sb1
        match_related:
          prefect.resource.id: monitor
        expect:
          - prefect.asset.materialization.succeeded
        parameters:
          event_id:
            template: '{{ event.id }}'
            __prefect_kind: jinja
          fan_out: true
```
**error**
```json
{'exception_message': 'Invalid request received.', 'exception_detail': [{'type': 'literal_error', 'loc': ['body', 'actions', 0, 'DoNothing', 'type'], 'msg': "Input should be 'do-nothing'", 'input': 'run-deployment', 'ctx': {'expected': "'do-nothing'"}}, {'type': 'value_error', 'loc': ['body', 'actions', 0, 'function-after[selected_deployment_requires_id(), RunDeployment]', 'parameters'], 'msg': "Value error, Invalid parameters: \nevent_id: Missing 'template' key in __prefect object", 'input': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'ctx': {'error': {}}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_deployment_requires_id(), PauseDeployment]', 'type'], 'msg': "Input should be 'pause-deployment'", 'input': 'run-deployment', 'ctx': {'expected': "'pause-deployment'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_deployment_requires_id(), ResumeDeployment]', 'type'], 'msg': "Input should be 'resume-deployment'", 'input': 'run-deployment', 'ctx': {'expected': "'resume-deployment'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'PauseScheduleForFlowRun', 'type'], 'msg': "Input should be 'pause-schedule-for-flow-run'", 'input': 'run-deployment', 'ctx': {'expected': "'pause-schedule-for-flow-run'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'ResumeSchedule', 'type'], 'msg': "Input should be 'resume-schedule-for-flow-run'", 'input': 'run-deployment', 'ctx': {'expected': "'resume-schedule-for-flow-run'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'ResumeSchedule', 'schedule_id'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'CancelFlowRun', 'type'], 'msg': "Input should be 'cancel-flow-run'", 'input': 'run-deployment', 'ctx': {'expected': "'cancel-flow-run'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'ChangeFlowRunState', 'type'], 'msg': "Input should be 'change-flow-run-state'", 'input': 'run-deployment', 'ctx': {'expected': "'change-flow-run-state'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'ChangeFlowRunState', 'state'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_work_queue_requires_id(), PauseWorkQueue]', 'type'], 'msg': "Input should be 'pause-work-queue'", 'input': 'run-deployment', 'ctx': {'expected': "'pause-work-queue'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_work_queue_requires_id(), ResumeWorkQueue]', 'type'], 'msg': "Input should be 'resume-work-queue'", 'input': 'run-deployment', 'ctx': {'expected': "'resume-work-queue'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendNotification', 'type'], 'msg': "Input should be 'send-notification'", 'input': 'run-deployment', 'ctx': {'expected': "'send-notification'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendNotification', 'block_document_id'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendNotification', 'body'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'CallWebhook', 'type'], 'msg': "Input should be 'call-webhook'", 'input': 'run-deployment', 'ctx': {'expected': "'call-webhook'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'CallWebhook', 'block_document_id'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_automation_requires_id(), PauseAutomation]', 'type'], 'msg': "Input should be 'pause-automation'", 'input': 'run-deployment', 'ctx': {'expected': "'pause-automation'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_automation_requires_id(), ResumeAutomation]', 'type'], 'msg': "Input should be 'resume-automation'", 'input': 'run-deployment', 'ctx': {'expected': "'resume-automation'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SuspendFlowRun', 'type'], 'msg': "Input should be 'suspend-flow-run'", 'input': 'run-deployment', 'ctx': {'expected': "'suspend-flow-run'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'ResumeFlowRun', 'type'], 'msg': "Input should be 'resume-flow-run'", 'input': 'run-deployment', 'ctx': {'expected': "'resume-flow-run'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'DeclareIncident', 'type'], 'msg': "Input should be 'declare-incident'", 'input': 'run-deployment', 'ctx': {'expected': "'declare-incident'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_work_pool_requires_id(), PauseWorkPool]', 'type'], 'msg': "Input should be 'pause-work-pool'", 'input': 'run-deployment', 'ctx': {'expected': "'pause-work-pool'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_work_pool_requires_id(), ResumeWorkPool]', 'type'], 'msg': "Input should be 'resume-work-pool'", 'input': 'run-deployment', 'ctx': {'expected': "'resume-work-pool'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_deployment_requires_id(), SlaViolation]', 'type'], 'msg': "Input should be 'sla-violation'", 'input': 'run-deployment', 'ctx': {'expected': "'sla-violation'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'function-after[selected_deployment_requires_id(), SlaViolation]', 'source'], 'msg': "Input should be 'inferred'", 'input': 'selected', 'ctx': {'expected': "'inferred'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendEmailNotification', 'type'], 'msg': "Input should be 'send-email-notification'", 'input': 'run-deployment', 'ctx': {'expected': "'send-email-notification'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotification', 'body'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotification', 'emails'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToUsersByPreference', 'type'], 'msg': "Input should be 'send-email-notification'", 'input': 'run-deployment', 'ctx': {'expected': "'send-email-notification'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToUsersByPreference', 'body'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToUsersByPreference', 'notification_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToSubscribers', 'type'], 'msg': "Input should be 'send-email-notification-to-subscribers'", 'input': 'run-deployment', 'ctx': {'expected': "'send-email-notification-to-subscribers'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToSubscribers', 'body'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToSubscribers', 'object_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendEmailNotificationToSubscribers', 'notification_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendPrefectNotification', 'type'], 'msg': "Input should be 'prefect-notification'", 'input': 'run-deployment', 'ctx': {'expected': "'prefect-notification'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendPrefectNotification', 'notification_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendPrefectNotification', 'message'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendTemplateEmailToSubscribers', 'type'], 'msg': "Input should be 'send-template-email-to-subscribers'", 'input': 'run-deployment', 'ctx': {'expected': "'send-template-email-to-subscribers'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendTemplateEmailToSubscribers', 'object_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendTemplateEmailToSubscribers', 'notification_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendTemplateEmailToUsersByPreference', 'type'], 'msg': "Input should be 'send-template-email-to-users-by-preference'", 'input': 'run-deployment', 'ctx': {'expected': "'send-template-email-to-users-by-preference'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendTemplateEmailToUsersByPreference', 'notification_type'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SlackNotificationToSubscribers', 'type'], 'msg': "Input should be 'slack-notification'", 'input': 'run-deployment', 'ctx': {'expected': "'slack-notification'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SlackSendNotificationToDefaultChannel', 'type'], 'msg': "Input should be 'slack-send-notification-to-default-channel'", 'input': 'run-deployment', 'ctx': {'expected': "'slack-send-notification-to-default-channel'"}}, {'type': 'literal_error', 'loc': ['body', 'actions', 0, 'SendIntegratedSlackMessageAction', 'type'], 'msg': "Input should be 'send-slack-message'", 'input': 'run-deployment', 'ctx': {'expected': "'send-slack-message'"}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendIntegratedSlackMessageAction', 'channel_id'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendIntegratedSlackMessageAction', 'subject'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}, {'type': 'missing', 'loc': ['body', 'actions', 0, 'SendIntegratedSlackMessageAction', 'body'], 'msg': 'Field required', 'input': {'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}}], 'request_body': {'name': 'run dlt load when dhub updated', 'description': '', 'enabled': True, 'tags': [], 'trigger': {'type': 'event', 'match': {'prefect.resource.name': 'ev_job_list_exp_sb1'}, 'match_related': {'prefect.resource.id': 'monitor'}, 'after': [], 'expect': ['prefect.asset.materialization.succeeded'], 'for_each': [], 'posture': 'Reactive', 'threshold': 1, 'within': 0.0}, 'actions': [{'type': 'run-deployment', 'source': 'selected', 'deployment_id': 'c343734f-b284-412b-88f7-c84846710d04', 'parameters': {'event_id': {'__prefect_kind': 'jinja'}, 'fan_out': True}, 'job_variables': None, 'schedule_after': 0.0}], 'actions_on_trigger': [], 'actions_on_resolve': [], 'owner_resource': 'prefect.deployment.c343734f-b284-412b-88f7-c84846710d04'}}
```

**Comment by zzstoatzz** [comment]
thanks for the report @rjgildea and @fredrikhgrelland - yes it seems likely that linked PR is the issue

will take a look

**Comment by zzstoatzz** [comment]
this should be fixed by the linked PR above, we'll get 3.6.4 out with this fix asap

sorry about the disruption!

**Comment by zzstoatzz** [comment]
[3.6.4 is released](https://pypi.org/project/prefect/3.6.4/)

**Comment by rcash** [comment]
still seeing issues in 3.6.4 with other fields and templating - referencing a variable for the value of `enabled` is broken

```yaml
deployments:
  - name: say-hello
    entrypoint: hello_flow.py:say_hello
    work_pool:
      name: my-work-pool
    triggers:
      - type: event
        enabled: "{{ prefect.variables.deployment_trigger_is_active }}"
        match:
          prefect.resource.id: hello.world
        expect:
          - external.resource.pinged
        parameters:
          name: "{{ event.name }}"
```

```bash
prefect --no-prompt deploy --all
Invalid fields in deployments:

  • say-hello: triggers

For valid deployment fields and examples, go to: https://docs.prefect.io/v3/concepts/deployments#deployment-schema

Skipping deployment configuration due to validation errors.
An entrypoint must be provided:

        prefect deploy path/to/file.py:flow_function

You can also provide an entrypoint in a prefect.yaml file.
```
