### ISSUE TITLE
`ValueError: Path /root/.prefect/storage/...` does not exist

### ISSUE THREAD

**Issue by caleb-recursion** [PrefectHQ/prefect#6086]
Prefect 2.0b15 has an issue where a task will occasionally fail if it cant find the serialized file. It almost looks like a race condition? Is the task starting before the file is written? The error will appear occasionally have ~100 or more tasks have executed, not consistently.

```
18:55:13.371 | DEBUG   | prefect.engine - Reported crashed task run 'mouse_detection-49dd9cf8-37-b6710e8b93d84a3ea96ea1d76f546466-1' successfully.
18:55:13.371 | INFO    | Task run 'mouse_detection-49dd9cf8-75' - Crash detected! Execution was interrupted by an unexpected exception.
18:55:13.372 | DEBUG   | Task run 'mouse_detection-49dd9cf8-75' - Crash details:
Traceback (most recent call last):
  File "/root/venv/lib/python3.8/site-packages/prefect_dask/task_runners.py", line 236, in wait
    return await future.result(timeout=timeout)
  File "/root/venv/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 957, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/root/venv/lib/python3.8/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/root/venv/lib/python3.8/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/root/venv/lib/python3.8/site-packages/prefect/filesystems.py", line 79, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/b371ce283437427e8f66dc8bb6de5d7c does not exist.
```

**Comment by bunchesofdonald** [comment]
@caleb-recursion Prefect 2 is out of beta now, have you run into these same issues?

**Comment by caleb-recursion** [comment]
Just confirmed it happens with 2.0.2

task 845/1000 failed

```
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/root/venv/lib/python3.8/site-packages/prefect/orion/schemas/states.py", line 145, in result
    raise data
  File "/root/venv/lib/python3.8/site-packages/prefect_dask/task_runners.py", line 236, in wait
    return await future.result(timeout=timeout)
  File "/root/venv/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 959, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/root/venv/lib/python3.8/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/root/venv/lib/python3.8/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/root/venv/lib/python3.8/site-packages/prefect/filesystems.py", line 147, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/523fe29629504a8486312fd5e0db8cc5 does not exist.

```

Ill try for a minimal example... its hard with a race condition, unless you think its not dask related.

**Comment by craigdalton** [comment]
I have been working on a Prefect 2.0 POC deployed to OpenShift with:

- Orion API server
- Orion agents
- Minio for Remote storage
- PostgresDB

Using this test flow deployed to an S3 bucket on the standalone Minio instance I was able to reproduce it quite consistently:

```python
import time
from prefect import flow, task, get_run_logger
import random

@task
def load_task(name):
    logger = get_run_logger()
    logger.info(f"Executing task on {name}!")
    time.sleep(random.randrange(3,10))
    logger.info(f"Task on {name} complete!")
    return name

@flow()
def main_flow(task_count):
    logger = get_run_logger()
    logger.info(f"Executing flow...")
    tasks = [f"task_{i}" for i in range(1, task_count + 1)]
    for future in load_task.map(tasks):
        future.wait()
    return

if __name__ == "__main__": 
    main_flow(50)
```

For example, using Postman to trigger the flow 10 times in quick succession to `{{prefect_host}}/api/deployments/:id/create_flow_run` with this payload:

```json
{
  "name": "Load Test Flow",
  "idempotency_key": "{{$guid}}",
  "parameters": {
      "name": "Load Testing"
  },
  "state": {
        "type": "SCHEDULED",
        "message":"Run through API"
    }
}
```

I got a crash on 1/10 flows:
![image](https://user-images.githubusercontent.com/47349238/183458126-01321765-04d0-4b9b-a9f4-f06c3f086d19.png)

Here is the debug output:

```
Crash details:
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 946, in begin_task_run
    return await orchestrate_task_run(
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 1079, in orchestrate_task_run
    state = await client.propose_state(
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/client.py", line 1770, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/task_runners.py", line 316, in _run_and_store_result
    self._results[run_key] = await run_fn(**run_kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 959, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/filesystems.py", line 147, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /opt/app-root/src/.prefect/storage/fabecc0c738c4a30af048739b2660a80 does not exist.
```

**Comment by madkinsz** [comment]
Interesting. For reference, this is failing here https://github.com/PrefectHQ/prefect/blob/38758c6527314abd97da3e791f227ca5afc947e7/src/prefect/engine.py#L955-L960

I'm a bit confused as from your code this task should never be completed already. Are your flows running on the same machine too? It's even more confusing that if the task run did match an existing run that the state's result would be invalid.

**Comment by madkinsz** [comment]
@caleb-recursion Can you share the `TaskRun` and `State` entries for that task run id?

**Comment by craigdalton** [comment]
> Interesting. For reference, this is failing here
> 
> https://github.com/PrefectHQ/prefect/blob/38758c6527314abd97da3e791f227ca5afc947e7/src/prefect/engine.py#L955-L960
> 
> I'm a bit confused as from your code this task should never be completed already. Are your flows running on the same machine too? It's even more confusing that if the task run did match an existing run that the state's result would be invalid.

I am using Prefect 2.0.3. I have the following pods running on OpenShift:

- 2 orion agents
- 1 orion late runs service

  ```
  - '--no-scheduler'
  - '--analytics-off'
  - '--late-runs'
  - '--no-ui'
  ```

- 1 orion scheduler

  ```
  - '--scheduler'
  - '--analytics-off'
  - '--no-late-runs'
  - '--no-ui'
  ```

- 1 orion ui

  ```
  - '--no-scheduler'
  - '--analytics-off'
  - '--no-late-runs'
  - '--ui'
  ```

- 1 minio standalone instance
- 1 postgresDB

This is because, initially we were getting 500 errors from the Orion API when loading it, so I split out in to separate services and did more load testing. I am using a single queue with a concurrency limit set at 50.

**Comment by lance0805** [comment]
I think this is because the default storage for the engine is local storage, so the task results are only retained on the machine where it is executed
https://github.com/PrefectHQ/prefect/blob/387e2f9e6907979214b2e1bb9c8b1beffaf597c9/src/prefect/engine.py#L332

**Comment by madkinsz** [comment]
Yeah the task results aren't available on another machine, but why is this task being loaded from another machine? Are you using the `cache_key_fn`?

**Comment by craigdalton** [comment]
> Yeah the task results aren't available on another machine, but why is this task being loaded from another machine? Are you using the `cache_key_fn`?

I don't believe so (at least not explicitly/intentionally).  My complete code example is [in my comment](https://github.com/PrefectHQ/prefect/issues/6086#issuecomment-1208317835) and the is no more to it than that.  Just created flow runs from the deployment repeatedly using the REST API with the payload I posted.  Postman generates a unique guid on every POST.

**Comment by madkinsz** [comment]
Can you share details per https://github.com/PrefectHQ/prefect/issues/6086#issuecomment-1208336327 for the task run that fails

**Comment by caleb-recursion** [comment]
@madkinsz Thanks. Its deploying in a few places and pulling from dockerhub. Ill have to build a version of the image with your changes unless you have one available?

Any idea why the task isn't trying when `retries=3` is set?

**Comment by caleb-recursion** [comment]
I installed the git main branch into the flow run containers, dask workers, and orion agent, I didn't see the log output you added anywhere. I have PREFECT_LOGGING_LEVEL=DEBUG . Is it possibly failing before that?

**Comment by madkinsz** [comment]
This exception is occurring outside your code so retries aren't handled.

I believe there's an open issue with retrieving logs from Dask. This occurs without the Dask task runner, correct?

You could also use the API/client to query for the task runs in your failed flow run then share the failed one. No need to reproduce again.

**Comment by caleb-recursion** [comment]
>This exception is occurring outside your code so retries aren't handled.

Makes sense

> I believe there's an open issue with retrieving logs from Dask. This occurs without the Dask task runner, correct?

I've only been trying it with the DaskTaskRunner. I can test.

>You could also use the API/client to query for the task runs in your failed flow run then share the failed one. No need to reproduce again.

Im not sure I understand. Share the url to it?

**Comment by caleb-recursion** [comment]
It seems it fails the same way in a different spot with your debug code in place.

```
Crash details:
Traceback (most recent call last):
  File "/root/venv/lib/python3.8/site-packages/prefect_dask/task_runners.py", line 236, in wait
    return await future.result(timeout=timeout)
  File "/root/venv/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 959, in begin_task_run
    get_run_logger(flow_run_context).debug(
  File "/root/venv/lib/python3.8/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/root/venv/lib/python3.8/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/root/venv/lib/python3.8/site-packages/prefect/filesystems.py", line 147, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/0bb5de7d6c5e48c4ad751e6221b43ebc does not exist.
```

**Comment by caleb-recursion** [comment]
This does not occur with the default task runner executing on the same k8s cluster. The flow completes successfully.

Also, this seems to be happening more frequently in the newer updates.

**Comment by caleb-recursion** [comment]
Hi again, I was testing random stuff and I added a `sleep 60` timer after the call to the dask worker in the container command, and it seems to happen less. It would still occur if I gave it a lot of tasks, 10k or more, but 100 tasks works every time.  Is there any chance the dask workers are being killed before a file is being flushed to disk? Is there any logic to confirm the state is written before exiting?

**Comment by caleb-recursion** [comment]
I updated to Prefect 2.0.4 and changed a few other things in the cluster. After recreating it seems to handle 1000 tasks reliably. 

I imagine its probably the update that resolved it, so try that first @craigdalton. A couple other things I changed were (i) increasing node size (ii) add 1 min keep alive after container exits (iii) Updated version of cuda base images (11.3.1)


However, at roughly 2-3k tasks it throws a new error:

```
Traceback (most recent call last):
  File "/root/venv/lib/python3.8/site-packages/prefect_dask/task_runners.py", line 236, in wait
    return await future.result(timeout=timeout)
  File "/root/venv/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 959, in begin_task_run
    get_run_logger(flow_run_context).debug(
  File "/root/venv/lib/python3.8/site-packages/prefect/logging/loggers.py", line 91, in get_run_logger
    raise RuntimeError("There is no active flow or task run context.")
RuntimeError: There is no active flow or task run context.
```

Is there a timeout somewhere that needs to be raised? Let me know if you want me to make a new issue for that.

**Comment by madkinsz** [comment]
Thanks for continuing to share updates.

That's a _very_ weird error since we explicitly pass the flow run context to the logger retrieval call. I'll look into that one separately.

**Comment by madkinsz** [comment]
>  Is there any chance the dask workers are being killed before a file is being flushed to disk? Is there any logic to confirm the state is written before exiting?

This is possible but unlikely, we write the result to disk before reporting the state. I'm mostly confuse that your task runs  are attempting to retrieve cached data at all. This should not be occurring from what you've shared.

**Comment by madkinsz** [comment]
I suspect what is happening here is that Dask is executing the task run multiple times and we are aborting the second run then attempting to retrieve the result from the first run which occurred on a different worker. I thought that the Dask task runner was robust to this, but I'll have to re-examine its behavior.

**Comment by craigdalton** [comment]
@caleb-recursion - the 2.0.4 update did not resolve my issues.  I am still able to reproduce the issue with 20 flows runs, each with 50 tasks (which just log and sleep as per my code sample).

**Comment by topher-lo** [comment]
Also getting this same error (Prefect 2.2.0, KubernetesJob, tested on both default and Dask task runners), not sure if this helps but noticed that I only get this error for flows that take longer than ~5:35 min to run... Are there any timeout / magic config numbers related to `.prefect/storage` that might be set to 335 seconds?

<img width="302" alt="Screenshot 2022-09-06 162056" src="https://user-images.githubusercontent.com/46541035/188584847-1057d752-31d3-4296-b9fa-b54c2552aa76.png">

Traceback:

**Comment by madkinsz** [comment]
> Are there any timeout / magic config numbers related to anyio or prefect.engine at the task level that might be set to 330 seconds?

Not that I know of.

**Comment by topher-lo** [comment]
@madkinsz A few more observations that might help:

**Comment by caleb-recursion** [comment]
Has the worker started at 5 minutes and 30 seconds? Or is it still creating? Maybe its related to the dask worker TTL? https://docs.dask.org/en/stable/configuration.html#distributed.scheduler.worker-ttl

**Comment by topher-lo** [comment]
> Has the worker started at 5 minutes and 30 seconds? Or is it still creating? Maybe its related to the dask worker TTL? https://docs.dask.org/en/stable/configuration.html#distributed.scheduler.worker-ttl

@caleb-recursion Unfortunately it doesn't seem to be a Dask issue. We aren't using Dask in this flow: neither as a task runner nor within any task. It's pure Prefect with the default task runner and Pandas. However, can confirm this exact same crash occurs with Dask task runner.

**Comment by topher-lo** [comment]
UPDATE: Turns out the error was entirely due to some k8s container configs. Really sorry for the trouble (note: the root cause of our error is probably unrelated to @caleb-recursion). We customized the k8s container spec with a `readinessProbe` and `livenessProbe`. These are the default settings we use for our FastAPI k8s deployment. However, it seems that they do not play well with Prefect and the k8s cluster prematurely destroys "successful" pods. The symptom of k8s destroying the pod is the `[alueError: Path /root/.prefect/storage/... does not exist` error (and a "crashed" state for the very first task).
```json
{
    "name": "prefect-job",
    "ports": [{"containerPort": 8888, "protocol": "TCP"}],
    "readinessProbe": {
        "tcpSocket": {"port": 8888},
        "initialDelaySeconds": 10,
        "periodSeconds": 10,
        "timeoutSeconds": 5,
        "successThreshold": 1,
        "failureThreshold": 5
    },
    "livenessProbe": {
        "tcpSocket": {"port": 8888},
        "initialDelaySeconds": 15,
        "periodSeconds": 20,
        "timeoutSeconds": 5,
        "successThreshold": 1,
        "failureThreshold": 5
    }
}
```
We removed the two probes and our flow runs were working again. From this experience here (and this [thread from slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1662137743080059)), perhaps this specific `ValueError: Path... does not exist` is the first exception that is raised whenever the flow run's server crashes?

**Comment by madkinsz** [comment]
Looks like this is resolved; we'll track rerunning tasks when cached results are missing in https://github.com/PrefectHQ/prefect/issues/8637 for now

**Comment by lucasdepetrisd** [comment]
I'm having the same problem. I have a custom API URL and PREFECT_HOME

![image](https://github.com/user-attachments/assets/58d8ea49-c575-4ee7-9717-cd74c1ae4b5c)

**Comment by cicdw** [comment]
@lucasdepetrisd what version of Prefect are you using? In 3.0, you may still see that error but it shouldn't result in task or flow failure; we can do a better job
Of suppressing it too.

**Comment by lucasdepetrisd** [comment]
Hi @cicdw thanks for the explanation. I'm using 3.0 but I'll ignore it as you suggested. Thanks again!
