### ISSUE TITLE
CircleCI is skipping builds for commits to our 1.x branch

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#6190]
### Describe the bug

When we merge a commit into the 1.x branch, CircleCI should build docker images. However, it now skips these builds because the branch doesn't have associated PRs.

### To Reproduce

```python
An example build: https://app.circleci.com/pipelines/github/PrefectHQ/prefect/12364/workflows/55e6ac7c-e177-42df-849c-72dfe85c3ab6/jobs/150758

You can also run:
git checkout prefect
git branch --contains aa60df895e2d0cc86d8c6792dd0184d6b92a90e0 --points-at 1.x | grep 1.x | wc -l
error: malformed object name '1.x'
       0
```

### Error

```
git branch --contains aa60df895e2d0cc86d8c6792dd0184d6b92a90e0 --points-at 1.x | grep 1.x | wc -l
error: malformed object name '1.x'
       0
``` 

### Versions

- OS: Alpine Linux
- Python: NA
- Prefect: 1.x

**Comment by abrookins** [comment]
Fixed by #6191

**Comment by madkinsz** [comment]
This doesn't fix builds on the commits; just fixes builds for releases.
