### ISSUE TITLE
Block checksum changes not compatible with old nested block schemas 

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#6265]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

EDIT: This bug was reported in the process of releasing `2.0.3`. The `2.0.3` official release does not contain this bug.

The `2.0.3` release made updates to block schema checksum logic. This means blocks created on older versions do not have a checksum that matches with `2.0.3` clients.

If the Orion database (whether open source or in cloud) has old block schema definitions, attempts to save blocks from new clients will not work.

This appears to only be an issue with nested blocks. I was able to save a `String` document correctly.

### Reproduction

```python
1. Login to Prefect Cloud with a workspace created before 8/5 OR connect to any Orion server with block schemas created before `2.0.3`
2. Upgrade your `prefect` version to `2.0.3`.
3. Attempt to save a docker container block


from prefect.blocks.core import Block
b = Block.load('docker-container/i-already-created-this')
b.save('test-saving') # throws exception
```

### Error

```
PrefectHTTPStatusError: Client error '409 Conflict' for url 'https://api.prefect.cloud/api/accounts/dbedf0dc-eb59-486d-9608-2f9eb4c97d08/workspaces/48c97f4c-2d83-4abe-8f76-a45221a44cc1/block_schemas/'
Response: {'detail': 'Identical block schema already exists.'}
For more information check: https://httpstatuses.com/409

The above exception was the direct cause of the following exception:

ObjectAlreadyExists                       Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 bnew.save('test-saving-new-block')

File ~/prefect/prefect/src/prefect/utilities/asyncutils.py:193, in sync_compatible.<locals>.wrapper(*args, **kwargs)
    189     return run_async_from_worker_thread(async_fn, *args, **kwargs)
    190 else:
    191     # In a sync context and there is no event loop; just create an event loop
    192     # to run the async code then tear it down
--> 193     return run_async_in_new_loop(async_fn, *args, **kwargs)

File ~/prefect/prefect/src/prefect/utilities/asyncutils.py:140, in run_async_in_new_loop(__fn, *args, **kwargs)
    139 def run_async_in_new_loop(__fn: Callable[..., Awaitable[T]], *args: Any, **kwargs: Any):
--> 140     return anyio.run(partial(__fn, *args, **kwargs))

File /opt/homebrew/Caskroom/miniconda/base/envs/py39orion/lib/python3.9/site-packages/anyio/_core/_eventloop.py:56, in run(func, backend, backend_options, *args)
     54 try:
     55     backend_options = backend_options or {}
---> 56     return asynclib.run(func, *args, **backend_options)
     57 finally:
     58     if token:

File /opt/homebrew/Caskroom/miniconda/base/envs/py39orion/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:233, in run(func, debug, use_uvloop, policy, *args)
    230         del _task_states[task]
    232 _maybe_set_event_loop_policy(policy, use_uvloop)
--> 233 return native_run(wrapper(), debug=debug)

File /opt/homebrew/Caskroom/miniconda/base/envs/py39orion/lib/python3.9/asyncio/runners.py:44, in run(main, debug)
     42     if debug is not None:
     43         loop.set_debug(debug)
---> 44     return loop.run_until_complete(main)
     45 finally:
     46     try:

File /opt/homebrew/Caskroom/miniconda/base/envs/py39orion/lib/python3.9/asyncio/base_events.py:647, in BaseEventLoop.run_until_complete(self, future)
    644 if not future.done():
    645     raise RuntimeError('Event loop stopped before Future completed.')
--> 647 return future.result()

File /opt/homebrew/Caskroom/miniconda/base/envs/py39orion/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:228, in run.<locals>.wrapper()
    225     task.set_name(task_state.name)
    227 try:
--> 228     return await func(*args)
    229 finally:
    230     del _task_states[task]

File ~/prefect/prefect/src/prefect/blocks/core.py:724, in Block.save(self, name, overwrite)
    712 @sync_compatible
    713 async def save(self, name: str, overwrite: bool = False):
    714     """
    715     Saves the values of a block as a block document.
    716 
   (...)
    722 
    723     """
--> 724     document_id = await self._save(name=name, overwrite=overwrite)
    726     return document_id

File ~/prefect/prefect/src/prefect/blocks/core.py:677, in Block._save(self, name, is_anonymous, overwrite)
    673 self._is_anonymous = is_anonymous
    674 async with prefect.client.get_client() as client:
    675 
    676     # Ensure block type and schema are registered before saving block document.
--> 677     await self.register_type_and_schema(client=client)
    679     try:
    680         block_document = await client.create_block_document(
    681             block_document=self._to_block_document(name=name)
    682         )

File ~/prefect/prefect/src/prefect/blocks/core.py:637, in Block.register_type_and_schema(cls, client)
    633     block_schema = await client.read_block_schema_by_checksum(
    634         checksum=cls._calculate_schema_checksum()
    635     )
    636 except prefect.exceptions.ObjectNotFound:
--> 637     block_schema = await client.create_block_schema(
    638         block_schema=cls._to_block_schema(block_type_id=block_type.id)
    639     )
    641 cls._block_schema_id = block_schema.id

File ~/prefect/prefect/src/prefect/client.py:1029, in OrionClient.create_block_schema(self, block_schema)
   1027 except httpx.HTTPStatusError as e:
   1028     if e.response.status_code == status.HTTP_409_CONFLICT:
-> 1029         raise prefect.exceptions.ObjectAlreadyExists(http_exc=e) from e
   1030     else:
   1031         raise

ObjectAlreadyExists: 
```

### Versions

```
Version:             2.0.1+219.g82dd3f526
API version:         0.8.0
Python version:      3.9.12
Git commit:          82dd3f52
Built:               Fri, Aug 5, 2022 4:40 PM
OS/Arch:             darwin/arm64
Profile:             cloud1
Server type:         hosted
```

**Comment by discdiver** [comment]
Great writeup, @zangell44! For users upgrading to 2.0.3, this is not an issue because the code leading to the problem was removed before the release, correct?

**Comment by desertaxle** [comment]
@discdiver that's correct. The code causing this issue was reverted in #6269

**Comment by zangell44** [comment]
Closing as this is resolved by Alex' work

**Comment by felix-ht** [comment]
@zangell44 i am still getting this error on version 2.3.2

Seems to happen with all blocks that were created with 2.0.3 python

**Comment by desertaxle** [comment]
@felix-ht as long as your blocks are loading correctly that warning can be safely ignored. We've updated the block schema for many blocks, but they should still be backwards-compatible with older block documents. Please open an issue if you encounter a scenario where you are not able to load an older block document with a newer version of Prefect.

**Comment by felix-ht** [comment]
@desertaxle what would be the best way to get rid of the warnings? Do I have to recreate all the blocks?
