### ISSUE TITLE
Can't change non-string options in DockerContainer block

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect#7200]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The boolean toggles for auto remove and stream output can't be changed.

### Reproduction

Running local orion instance with sqlite database.

1. Create a new Docker Container block, set auto remove to `true` and stream output to `true`
2. Edit the block and set auto remove to `false`
3. Save
4. "Block updated successfully" displayed but the auto remove setting stays `true` ❌ 
5. Edit the block once again and set stream output to `false`
6. Save
7. "Block updated successfully" displayed but the stream output setting was set to  `false` ✔️ 
8. Edit the block once again and set stream output to `true`
9. Save
10. "Block updated successfully" displayed but the stream output setting stays `false` ❌ 

### Error

After create:
![image](https://user-images.githubusercontent.com/18382402/196194729-4d68b7ec-cc01-403b-92ad-aea7dbe49e9d.png)

After setting auto remove to `false`:
![image](https://user-images.githubusercontent.com/18382402/196194853-4423af2c-eba8-4137-b4f9-dfa8eec8d7db.png)

After setting stream output to `false`:
![image](https://user-images.githubusercontent.com/18382402/196194931-41cdd82a-32e7-4200-a9e0-0d7d6693c179.png)

After setting stream output to `true`:
![image](https://user-images.githubusercontent.com/18382402/196195030-3c5b08a8-f6c7-4e2d-b869-13d106c551b8.png)

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
2.6.1
```

**Comment by sti0** [comment]
This also relies on networks and commands etc. they can be added but the can't deleted fully. If I added multiple commands I can delete them one by one until the last one, this cant be deleted.
![image](https://user-images.githubusercontent.com/18382402/196196840-43f64f42-64fa-43b8-9e6a-de16d0515545.png)
![image](https://user-images.githubusercontent.com/18382402/196196898-3943a570-f5da-481a-bbee-69526944bc69.png)
![image](https://user-images.githubusercontent.com/18382402/196196936-704fdef1-6e2d-4394-8922-f9a478decd22.png)
![image](https://user-images.githubusercontent.com/18382402/196196971-b2672ffe-ca2c-45b9-a0cd-c831d6d783fc.png)
![image](https://user-images.githubusercontent.com/18382402/196197003-16db6452-912f-4102-8cd0-fb61376eace4.png)

**Comment by madkinsz** [comment]
Perhaps a duplicate of https://github.com/PrefectHQ/prefect/issues/7043

**Comment by madkinsz** [comment]
@pleek91 is this resolved by your pull request for #7043?

**Comment by pleek91** [comment]
Confirmed this is not fixed and also confirmed this is an issue with how we're attempting to patch blocks in the ui/api. @desertaxle this is one of the issues we could fix with a post block endpoint. 

cc @zhen0

**Comment by pleek91** [comment]
I believe this will be closed by https://github.com/PrefectHQ/orion-design/pull/818 @zhen0
