### ISSUE TITLE
Automation trigger is fired on long "running" state when not needed

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8495]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We have created this automation rule, to send us an email when a flow stays in RUNNING state for more than 2 hours:

![CleanShot 2023-02-11 at 11 19 30@2x](https://user-images.githubusercontent.com/5398977/218250599-095ed02f-193b-4c0e-9630-b314f79bd806.jpg)

![CleanShot 2023-02-11 at 11 20 26@2x](https://user-images.githubusercontent.com/5398977/218250623-c8885e78-abcc-4d78-9429-8bb6922d78c3.jpg)

So next, the alert was triggered on some flow:

![CleanShot 2023-02-11 at 11 22 36@2x](https://user-images.githubusercontent.com/5398977/218250765-5d58e508-155f-4b75-8b41-d5f2fbd4d0ce.jpg)

But when we look at the flow, we can see that it only runs for about 2 minutes and there are no signs for running that long:

![CleanShot 2023-02-11 at 11 26 30@2x](https://user-images.githubusercontent.com/5398977/218250899-a234ae9e-d095-4646-a849-fcce30333bc2.jpg)

Also here is the full log:

![CleanShot 2023-02-11 at 11 28 26@2x](https://user-images.githubusercontent.com/5398977/218250944-e181b377-d218-40a3-9cab-9be3ca09c21e.jpg)

This is the flow url:
https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/fe21cc1b-d31a-4339-96c4-78601ee057a5

### Reproduction

```python3
Create the trigger as I've described above, and wait for it to trigger accidentally/
```

### Versions

```Text
Prefect Cloud
```

**Comment by taljaards** [comment]
Duplicate of https://github.com/PrefectHQ/prefect/issues/8217

**Comment by billpalombi** [comment]
Thanks for reporting this @yaronlevi. We have replicated this on our end and are actively working on a solution. We'll report back once its addressed.

**Comment by yaronlevi** [comment]
I think this is the same bug.

This automation cancels long-running flows:

![CleanShot 2023-02-28 at 14 15 06@2x](https://user-images.githubusercontent.com/5398977/221851854-8bc60311-fa7e-427f-8cd5-7aa32946c401.jpg)

And it was triggered on this flow:

![CleanShot 2023-02-28 at 14 16 00@2x](https://user-images.githubusercontent.com/5398977/221852062-a5c3e7a4-78db-403f-80a4-c6ec3667048d.jpg)

But this flow was running just fine, and finished in success state:

![CleanShot 2023-02-28 at 14 17 51@2x](https://user-images.githubusercontent.com/5398977/221852319-2ce73b49-d632-43b3-8d9d-b47859ffd0ef.jpg)

Flow ID: ecd0afaf-9b2c-4ae6-ad88-cb5c275e6f2b
Flow run ID: ddecf0f6-b11e-4431-8951-11365d34a9c0
Flow run URL: https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/ddecf0f6-b11e-4431-8951-11365d34a9c0

**Comment by billpalombi** [comment]
Yes, this appears to be the same bug. Thanks for the example.

**Comment by chrisguidry** [comment]
Thanks, @yaronlevi yep I just confirmed this is the same issue, and we're very very close on a resolution, I'm looking at today or tomorrow for the release.

**Comment by yaronlevi** [comment]
@chrisguidry yes, and specifically today it's just gone completely crazy and continuously triggering when not needed 😬

![CleanShot 2023-02-28 at 19 12 56@2x](https://user-images.githubusercontent.com/5398977/221927315-40db942d-a879-4fcd-8192-0b23ae218c01.jpg)

Please contact us if you need any more debug info. We would happily help.

**Comment by chrisguidry** [comment]
So sorry about that, @yaronlevi.  The good news is that this afternoon we released two changes that should resolve the erroneous firing of proactive triggers.  I am cautiously optimistic, and I would love to hear back from you in another day or two to let us know if you're seeing an improvement as well.

**Comment by yaronlevi** [comment]
@chrisguidry Sure, I'll keep an eye on our automation and report if I am still seeing it.

**Comment by chrisguidry** [comment]
I believe we've addressed the most common reasons for these, and we'll re-open new issues for specific cases.
