### ISSUE TITLE
Add "Delete" to the overflow menu for each flow in the list on the flows page

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#9518]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

To delete a single flow, I have to hover over it, select the check box, then select the delete icon. 

### Describe the proposed behavior

I can select the three dot menu on any flow and select "Delete"

**Comment by AmanSal1** [comment]
@billpalombi can i work on this ?

**Comment by billpalombi** [comment]
Hi @AmanSal1, absolutely! We would appreciate it!

**Comment by madkinsz** [comment]
@billpalombi I'm presuming this is a UI change, @AmanSal1 the UI changes often require work over in https://github.com/PrefectHQ/prefect-ui-library — please let us know if you need help getting started.

**Comment by billpalombi** [comment]
Yes, it is a UI change

**Comment by AmanSal1** [comment]
@billpalombi @madkinsz  okay !! when I started i was bit confused about how the ui is designed but then i got to know about all the repositories from the the package file . I have started working on it will  update you soon with the progress

**Comment by AmanSal1** [comment]
@madkinsz i wanted to know that how are the two libraries linked like i have found the file which has to be changed in  https://github.com/PrefectHQ/prefect-ui-library but how can we  see the changes locally like i am unable to locate this prefect-ui-library on my computer for the changes that are need to be made in the file . Need some help here

**Comment by zhen0** [comment]
@AmanSal1 - so happy to have you working on the UI!  

The instructions for linking your packages are in the readme of the prefect-ui-library but I realize it can be a bit confusing so any feedback on how we could improve the instructions is very welcome. I'm copying the instructions here:

If you plan to develop against the Prefect UI you can install the prefect-ui-library package locally.  We recommend using the cli and running:

`npm i @prefecthq/prefect-ui-library@../../prefect-ui-library --save
`
in the `Prefect UI` project. You will need to replace `../../prefect-ui-library` with whatever is the relative path from your Prefect UI project’s directory to the prefect-ui-library project directory on your computer. You can also use an absolute path.

If you have done this successfully, you should see your Prefect UI package.json and package-lock.json updated to show your local prefect-ui-library.

💡 Keep in mind this will update both the package.json and package-lock.json files. Be sure to not commit the changes to these two files.

💡 Linking a package this way is the safest as it avoids having to do an npm i.

Then when linking prefect-ui-library to the prefect/UI project you can do the following:

In prefect-ui-library (this repo):

npm run dev

In [ui](https://github.com/PrefectHQ/prefect/tree/main/UI):

npm run serve

**Comment by zhen0** [comment]
I've assigned this to you @AmanSal1 so that we know somebody is working on it but do please reach out if you have any more questions.

**Comment by AmanSal1** [comment]
@zhen0 I had followed the steps till linking the package  but on run the command "npm run dev"
in the prefect -ui-library repo i got some error . Can you help me out attaching the screenshot.

One more thing I first cloned  "https://github.com/PrefectHQ/prefect" after that I cloned "https://github.com/PrefectHQ/prefect-ui-library" in the same folder ran the command "npm i @prefecthq/prefect-ui-library@../../prefect-ui-library --save " by changing the " ../../prefect-ui-library" with the path of the prefect-ui-library repo till here it ran successfully .


![Capture](https://github.com/PrefectHQ/prefect/assets/121633121/674bbac5-9d9e-4ed5-867f-d890cb0eb4f3)

**Comment by zhen0** [comment]
Thanks for flagging @AmanSal1 - it looks as though there is a type incompatibility between the latest version of our component library and the prefect-ui-library.  Sorry about the confusion there.  If you pin to the version in the package.json or 1.8.2 you should be good - you can run `npm i @prefecthq/prefect-design@1.8.2` to do that.

**Comment by zhen0** [comment]
Let me know if that helps or you see any other issues.

**Comment by pleek91** [comment]
Thanks for calling that out. Fixed by https://github.com/PrefectHQ/prefect-ui-library/pull/1445

**Comment by AmanSal1** [comment]
@zhen0 I tried running  it again after doing what you said but unfortunately I encountered  few errors again . Here are some screenshot

![Capture 1](https://github.com/PrefectHQ/prefect/assets/121633121/0fd006c1-e74d-4b83-bd95-c1b9faf63bee)

**Comment by zhen0** [comment]
@AmanSal1 - the issue that Craig linked should fully fix this.  Can you pull the ui-library from main and than run `npm ci`

If that doesn't resolve it, perhaps we should do a quick sync check in - I'm free this afternoon if it's helpful!

**Comment by zhen0** [comment]
Ok @AmanSal1 - that looks like it's working to me but we've got you so far and I want to make sure we set you up to succeed.  I'll be hanging in this google meet for the next hour or so if you want help on this: 

Jenny office hours
Wednesday, May 24 · 2:30 – 3:30pm
Time zone: America/New_York
Google Meet joining info
Video call link: https://meet.google.com/dou-tfmw-ykt
Or dial: ‪(US) +1 409-433-9169‬ PIN: ‪627 179 996‬#
More phone numbers: https://tel.meet/dou-tfmw-ykt?pin=5029436478547

**Comment by AmanSal1** [comment]
@zhen0 So i started from the beginning and all the error were resolved and its running perfectly. 
But i would like to know  how you create the flow because i have created a one but it is not showing on the front end basically on the server . 

I ran npm run dev in one terminal and npm run serve in another according to their repositories 
and created a python script for flow and then i ran the python file .I guess i am going wrong somewhere need your assistance  .I am attaching all the screenshot 

I even tried running the "prefect dev ui" command in the prefect folder but it had the same results .



![21](https://github.com/PrefectHQ/prefect/assets/121633121/41894b07-1e46-4ea4-b6c2-c96b648b2f2f)
![22](https://github.com/PrefectHQ/prefect/assets/121633121/5bbecf86-904a-472e-bd9c-3dd53054fb7c)
![23](https://github.com/PrefectHQ/prefect/assets/121633121/b73b276b-a905-42da-9bab-5c319048eaf8)
![24](https://github.com/PrefectHQ/prefect/assets/121633121/5552e7f2-13f8-458b-94df-dc9fdc830d12)

**Comment by zhen0** [comment]
Hi @AmanSal1 - Did you run `prefect server start`? You'll need to do that in another terminal window in the same environment that you're running your flow etc. 

https://docs.prefect.io/latest/host

**Comment by AmanSal1** [comment]
@zhen0 Apparently after I closed my code editor and then ran the command again I got the same error that were persisting earlier . I dont know what happened but npm run serve is giving the same errors.

Flow:
1.Cloned prefect
2.Ran "pip install -e ".[dev]"
3.Cloned prefect-ui-library in separate folder
4. Ran "npm i @prefecthq/prefect-ui-library@../../prefect-ui-library --save " by chaning the path and running it in the prefect ui

**Comment by zhen0** [comment]
Ok. Let's take a step back. Perhaps we don't need to go through the hassle of linking repos to get you started. 

You can run npm run serve from the prefect-ui-library which will pull up our demo page. 

You should be able to see a flow load item and its menu button. That's where you'd be adding the delete.

**Comment by zhen0** [comment]
![image](https://github.com/PrefectHQ/prefect/assets/40272060/d2cf98a5-3286-4f52-839f-4fe0011585b6)

**Comment by AmanSal1** [comment]
@zhen0 Yes !!! it is working fine now have made some progress towards the feature enhancement .Here are the some screenshot 

Added the delete label in the overflowmenu
![1](https://github.com/PrefectHQ/prefect/assets/121633121/c50efab5-f9cc-4620-9fed-95dee2f00c9c)

Confirmdeletemodel implemented with the delete label in the overflowmenu
![2](https://github.com/PrefectHQ/prefect/assets/121633121/9ca462ec-1fa3-452a-b977-5c3f4851abbb)

Is it alright ?

**Comment by zhen0** [comment]
Thanks! That looks like the right approach to me.  Could we add the flow name to the modal title so it's nice and clear? I think that should be possible as a prop.

**Comment by AmanSal1** [comment]
@zhen0 so i have implemented the delete feature in the overflowmenuitem but i am not sure how well i have implemented it like the logic and all . But here is glimpse of this is working .
If you want I can give you a screenshot of the code like how I have implemented it .

https://github.com/PrefectHQ/prefect/assets/121633121/47db4f26-b0e8-438b-b729-cd405dc1bc87

.

**Comment by zhen0** [comment]
Great. Would you be able to do a draft PR? That'll be easier to give feedback on than a screenshot.

**Comment by AmanSal1** [comment]
@zhen0  Yes, should i post this in prefect ui library repository ? And  like can you give me some brief steps of drafting  a PR ?

**Comment by zhen0** [comment]
What do you need to know @AmanSal1?

**Comment by zhen0** [comment]
Ah I see. You can push your code to a branch in the ui library and then open a PR for it. Then you can share a link to your PR there are reference this issue in your PR description.

**Comment by AmanSal1** [comment]
https://github.com/PrefectHQ/prefect-ui-library/pull/1478 
@zhen0 This is the link to my PR you can review it now .

**Comment by AmanSal1** [comment]
@zhen0 Thank you for the assistance. The code has been merged into the main branch. I would like to join the Slack channel, and I have requested an invite through my email. Could you please include me

**Comment by zhen0** [comment]
Closed by https://github.com/PrefectHQ/prefect-ui-library/pull/1478

Thank you @AmanSal1
