### ISSUE TITLE
"Getting started" link in docs sidebar nav doesn't work

### ISSUE THREAD

**Issue by cco3** [PrefectHQ/prefect#9598]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Navigation using the "Getting Started" link in the sidebar is interrupted

### Reproduction

```python3
- Visit https://docs.prefect.io/latest/tutorials/
- Click "Getting Started"

nothing changes; I would expect to actually navigate to https://docs.prefect.io/latest/

I can't reproduce the issue locally; (I have built the docs locally and the sidebar nav works fine.)
```

### Versions

```Text
2.10.9
```

**Comment by discdiver** [comment]
I can verify the same browser console behavior.

**Comment by jawnsy** [comment]
Those errors should be unrelated as browsers will ignore unknown features. I'm unable to reproduce this using Chrome Version 113.0.5672.126 (Official Build) (arm64)

What browser are you using? Do you have the same issue in incognito or private browsing mode? (These modes disable extensions by default, so this helps us rule out whether an extension is causing the issue)

**Comment by cco3** [comment]
Same behavior in incognito.  Running `Version 113.0.5672.63 (Official Build) (64-bit)`

**Comment by discdiver** [comment]
This is fixed in the latest netlify pre-release builds. Recent PRs unpinning mkdocks insiders probably fixed it. We shall see with the next Prefect release - probably on Thursday.

**Comment by serinamarie** [comment]
@jawnsy @discdiver I think this is still an issue. Can either of you reproduce still?

**Comment by discdiver** [comment]
Strange. It works fine for me for a while. Then it stops working. Then I refresh the page and it works again. Trying to see if I can figure out if there's a certain page expansion that is causing the problem.

**Comment by jawnsy** [comment]
Thanks to the reproduction that @discdiver did, I've figured out the problem - we were using `mike` incorrectly, we were deploying twice:

```
mike deploy -F ./mkdocs.insiders.yml --update-aliases --branch $branch_name --prefix=versions "$display_name"
mike deploy -F ./mkdocs.insiders.yml --update-aliases --branch $branch_name --prefix=versions latest
```

However, what we should've done is deploy once with `latest` as an alias, like so:

```
mike deploy --config-file ./mkdocs.insiders.yml --update-aliases --branch $branch_name --prefix=versions "$display_name" latest
```

This fix should now be live on https://docs.prefect.io

**Comment by tinvaan** [comment]
LGTM now - ok to close from my end. Thanks @jawnsy 🍾

**Comment by jawnsy** [comment]
Thanks for confirming quickly @tinvaan !
